# Generated by Django 4.2.7 on 2024-11-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BreakFast_app', '0006_rename_user_fastingtracker_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastingtracker',
            name='exercise_duration',
            field=models.IntegerField(blank=True, help_text='Exercise duration in minutes', null=True),
        ),
        migrations.AddField(
            model_name='fastingtracker',
            name='hunger_level',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='fastingtracker',
            name='stress_level',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='fastingtracker',
            name='water_intake',
            field=models.FloatField(blank=True, help_text='Water intake in liters', null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='daily_tasks',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='program',
            name='prerequisites',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='resources',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='program',
            name='rewards',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='program',
            name='success_stories',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='program',
            name='tips',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='achievements',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(choices=[('SEDENTARY', 'Sedentary'), ('LIGHT', 'Lightly Active'), ('MODERATE', 'Moderately Active'), ('VERY', 'Very Active'), ('EXTRA', 'Extra Active')], default='MODERATE', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='badges_earned',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fasting_reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(choices=[('WEIGHT_LOSS', 'Weight Loss'), ('MUSCLE_GAIN', 'Muscle Gain'), ('MAINTENANCE', 'Maintenance'), ('HEALTH', 'Overall Health'), ('ENERGY', 'Energy Management')], default='HEALTH', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='measurement_reminder_day',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='difficulty',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=20),
        ),
    ]
