# Generated by Django 4.2.7 on 2024-11-20 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BreakFast_app', '0008_user_contact_number_user_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sleeplog',
            options={'ordering': ['-sleep_time']},
        ),
        migrations.AddField(
            model_name='sleeplog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sleeplog',
            name='quality',
            field=models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Fair'), (4, 'Good'), (5, 'Excellent')], default=3),
        ),
    ]
