# Generated by Django 4.2.7 on 2024-11-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BreakFast_app', '0009_alter_sleeplog_options_sleeplog_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fastingtracker',
            name='energy_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (4, 'High')], null=True),
        ),
        migrations.AlterField(
            model_name='fastingtracker',
            name='mood',
            field=models.IntegerField(blank=True, choices=[(1, 'Bad'), (2, 'Okay'), (3, 'Good')], null=True),
        ),
    ]
