# Generated by Django 4.2.7 on 2024-11-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BreakFast_app', '0010_alter_fastingtracker_energy_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastingtracker',
            name='is_fasting',
            field=models.BooleanField(default=True),
        ),
    ]
