# Generated by Django 4.2.7 on 2024-11-23 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BreakFast_app', '0011_fastingtracker_is_fasting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SleepLog',
        ),
    ]
