# Generated by Django 4.2.7 on 2024-11-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BreakFast_app', '0014_alter_fastingplan_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailysurvey',
            name='hunger_level',
        ),
        migrations.RemoveField(
            model_name='dailysurvey',
            name='stress_level',
        ),
        migrations.AddField(
            model_name='dailysurvey',
            name='minutes_of_sleep',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailysurvey',
            name='energy_level',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AlterField(
            model_name='dailysurvey',
            name='hours_of_sleep',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailysurvey',
            name='mood',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
