# Generated by Django 4.2.7 on 2024-11-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BreakFast_app', '0015_remove_dailysurvey_hunger_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fastingtracker',
            name='hunger_level',
        ),
        migrations.RemoveField(
            model_name='fastingtracker',
            name='stress_level',
        ),
        migrations.AlterField(
            model_name='fastingtracker',
            name='energy_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Very High')], null=True),
        ),
        migrations.AlterField(
            model_name='fastingtracker',
            name='mood',
            field=models.IntegerField(blank=True, choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Neutral'), (4, 'Good'), (5, 'Very Good')], null=True),
        ),
    ]
