# Generated by Django 4.2.7 on 2024-12-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BreakFast_app', '0016_remove_fastingtracker_hunger_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightlog',
            name='weight_change',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
